#!/usr/bin/env bash
set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
STATE_DIR="${STATE_DIR:-$DOTFILES_DIR/machine-state}"
PLIST_DIR="$STATE_DIR/plists"
DEFAULTS_DIR="$STATE_DIR/defaults"
RUNTIME_DIR="$STATE_DIR/runtime"
METADATA_FILE="$STATE_DIR/metadata.env"
DEFAULTS_WRITE_SCRIPT="$DEFAULTS_DIR/apply-defaults-write.sh"
BREWFILE_PATH="$DOTFILES_DIR/Brewfile"
BACKUP_DATE="$(date '+%Y-%m-%d')"
BACKUP_TS="$(date '+%Y-%m-%d %H:%M:%S')"

mkdir -p "$PLIST_DIR" "$DEFAULTS_DIR" "$RUNTIME_DIR"

backup_plist() {
  local src="$1"
  local dst="$2"
  if [[ -f "$src" ]]; then
    cp -f "$src" "$dst"
  fi
}

trim_value() {
  printf "%s" "$1" | awk '{$1=$1; print}'
}

normalize_bool() {
  local raw="$1"
  case "$raw" in
    1|true|TRUE|yes|YES) printf "true" ;;
    0|false|FALSE|no|NO) printf "false" ;;
    *) return 1 ;;
  esac
}

if [[ -x "$DOTFILES_DIR/Scripts/machine-clean-generated.sh" ]]; then
  "$DOTFILES_DIR/Scripts/machine-clean-generated.sh" >/dev/null 2>&1 || true
fi

backup_plist "$HOME/Library/Preferences/com.apple.dock.plist" "$PLIST_DIR/com.apple.dock.snapshot.plist"
backup_plist "$HOME/Library/Preferences/com.apple.finder.plist" "$PLIST_DIR/com.apple.finder.snapshot.plist"
defaults export com.apple.dock "$PLIST_DIR/com.apple.dock.export.plist" >/dev/null 2>&1 || true
defaults export com.apple.finder "$PLIST_DIR/com.apple.finder.export.plist" >/dev/null 2>&1 || true

if command -v brew >/dev/null 2>&1; then
  brew bundle dump --force --file "$BREWFILE_PATH" >/dev/null
fi

DOMAINS=(
  "NSGlobalDomain"
  "com.apple.LaunchServices"
  "com.apple.NetworkBrowser"
  "com.apple.QuickTimePlayerX"
  "com.apple.Safari"
  "com.apple.SoftwareUpdate"
  "com.apple.appstore"
  "com.apple.commerce"
  "com.apple.desktopservices"
  "com.apple.dock"
  "com.apple.finder"
  "com.apple.universalaccess"
  "com.apple.DiskUtility"
)

for domain in "${DOMAINS[@]}"; do
  defaults read "$domain" >"$DEFAULTS_DIR/$domain.read.txt" 2>/dev/null || true
  defaults export "$domain" "$DEFAULTS_DIR/$domain.export.plist" >/dev/null 2>&1 || true
done

cat >"$DEFAULTS_WRITE_SCRIPT" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Generated by Scripts/machine-state-backup.sh at $BACKUP_TS
EOF

KEY_SPECS=(
  "com.apple.dock|springboard-rows|int"
  "com.apple.dock|springboard-columns|int"
  "com.apple.universalaccess|reduceTransparency|bool"
  "com.apple.dock|tilesize|int"
  "com.apple.LaunchServices|LSQuarantine|bool"
  "NSGlobalDomain|AppleFontSmoothing|int"
  "com.apple.dock|mouse-over-hilite-stack|bool"
  "com.apple.dock|expose-animation-duration|float"
  "com.apple.dock|expose-group-by-app|bool"
  "com.apple.dock|mru-spaces|bool"
  "com.apple.finder|AppleShowAllFiles|bool"
  "NSGlobalDomain|AppleShowAllExtensions|bool"
  "com.apple.finder|ShowStatusBar|bool"
  "com.apple.finder|ShowPathbar|bool"
  "com.apple.finder|_FXShowPosixPathInTitle|bool"
  "com.apple.finder|FXEnableExtensionChangeWarning|bool"
  "NSGlobalDomain|com.apple.springing.enabled|bool"
  "NSGlobalDomain|com.apple.springing.delay|float"
  "com.apple.desktopservices|DSDontWriteNetworkStores|bool"
  "com.apple.desktopservices|DSDontWriteUSBStores|bool"
  "com.apple.finder|WarnOnEmptyTrash|bool"
  "com.apple.NetworkBrowser|BrowseAllInterfaces|bool"
  "com.apple.Safari|AutoOpenSafeDownloads|bool"
  "com.apple.Safari|ShowFavoritesBar|bool"
  "com.apple.Safari|ShowSidebarInTopSites|bool"
  "com.apple.Safari|DebugSnapshotsUpdatePolicy|int"
  "com.apple.Safari|IncludeInternalDebugMenu|bool"
  "com.apple.Safari|IncludeDevelopMenu|bool"
  "com.apple.Safari|WebKitDeveloperExtrasEnabledPreferenceKey|bool"
  "com.apple.Safari|com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled|bool"
  "NSGlobalDomain|WebKitDeveloperExtras|bool"
  "com.apple.Safari|WebAutomaticSpellingCorrectionEnabled|bool"
  "com.apple.Safari|AutoFillFromAddressBook|bool"
  "com.apple.Safari|AutoFillPasswords|bool"
  "com.apple.Safari|AutoFillCreditCardData|bool"
  "com.apple.Safari|AutoFillMiscellaneousForms|bool"
  "com.apple.Safari|SendDoNotTrackHTTPHeader|bool"
  "com.apple.Safari|InstallExtensionUpdatesAutomatically|bool"
  "com.apple.Safari|WebKitJavaScriptCanOpenWindowsAutomatically|bool"
  "com.apple.Safari|com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically|bool"
  "com.apple.appstore|WebKitDeveloperExtras|bool"
  "com.apple.appstore|ShowDebugMenu|bool"
  "com.apple.SoftwareUpdate|AutomaticCheckEnabled|bool"
  "com.apple.SoftwareUpdate|ScheduleFrequency|int"
  "com.apple.SoftwareUpdate|AutomaticDownload|int"
  "com.apple.SoftwareUpdate|CriticalUpdateInstall|int"
  "com.apple.SoftwareUpdate|ConfigDataInstall|int"
  "com.apple.commerce|AutoUpdate|bool"
  "com.apple.commerce|AutoUpdateRestartRequired|bool"
  "com.apple.DiskUtility|DUDebugMenuEnabled|bool"
  "com.apple.DiskUtility|advanced-image-options|bool"
  "com.apple.QuickTimePlayerX|MGPlayMovieOnOpen|bool"
)

for spec in "${KEY_SPECS[@]}"; do
  IFS="|" read -r domain key value_type <<<"$spec"

  if ! raw_value="$(defaults read "$domain" "$key" 2>/dev/null)"; then
    printf "# skipped: defaults read %s %s\n" "$domain" "$key" >>"$DEFAULTS_WRITE_SCRIPT"
    continue
  fi

  first_line="$(printf "%s\n" "$raw_value" | head -n 1)"
  trimmed_value="$(trim_value "$first_line")"

  case "$value_type" in
    bool)
      if bool_value="$(normalize_bool "$trimmed_value")"; then
        printf "defaults write %q %q -bool %s\n" "$domain" "$key" "$bool_value" >>"$DEFAULTS_WRITE_SCRIPT"
      else
        printf "# skipped invalid bool: %s %s=%q\n" "$domain" "$key" "$trimmed_value" >>"$DEFAULTS_WRITE_SCRIPT"
      fi
      ;;
    int)
      if [[ "$trimmed_value" =~ ^-?[0-9]+$ ]]; then
        printf "defaults write %q %q -int %s\n" "$domain" "$key" "$trimmed_value" >>"$DEFAULTS_WRITE_SCRIPT"
      else
        printf "# skipped invalid int: %s %s=%q\n" "$domain" "$key" "$trimmed_value" >>"$DEFAULTS_WRITE_SCRIPT"
      fi
      ;;
    float)
      if [[ "$trimmed_value" =~ ^-?[0-9]+([.][0-9]+)?$ ]]; then
        printf "defaults write %q %q -float %s\n" "$domain" "$key" "$trimmed_value" >>"$DEFAULTS_WRITE_SCRIPT"
      else
        printf "# skipped invalid float: %s %s=%q\n" "$domain" "$key" "$trimmed_value" >>"$DEFAULTS_WRITE_SCRIPT"
      fi
      ;;
    string)
      printf "defaults write %q %q -string %q\n" "$domain" "$key" "$first_line" >>"$DEFAULTS_WRITE_SCRIPT"
      ;;
  esac
done

{
  echo
  echo "killall Dock >/dev/null 2>&1 || true"
  echo "killall Finder >/dev/null 2>&1 || true"
} >>"$DEFAULTS_WRITE_SCRIPT"

chmod +x "$DEFAULTS_WRITE_SCRIPT"

cat >"$METADATA_FILE" <<EOF
BACKUP_DATE="$BACKUP_DATE"
BACKUP_TS="$BACKUP_TS"
DOTFILES_DIR="$DOTFILES_DIR"
EOF
